### ISSUE TITLE
Unhandled rejection error

### ISSUE THREAD

**Issue by phillmac** [libp2p/js-libp2p-mplex#111]
https://github.com/libp2p/js-libp2p-mplex/blob/c44bf9a32b8fcaafee03ff190afad5a45bfb7799/src/stream.js#L76

This line occasionally throws an unhandled rejection:
```
Unhandled Rejection at Promise Promise {
  <rejected> AbortError: stream reset
      at abortable (/workspace/ipfs-bundle-t/node_modules/abortable-iterator/index.js:29:19)
      at abortable.next (<anonymous>)
      at Object.sink (/workspace/ipfs-bundle-t/node_modules/libp2p-mplex/src/stream.js:76:24)
      at runMicrotasks (<anonymous>)
      at processTicksAndRejections (internal/process/task_queues.js:97:5) {
    type: 'aborted',
    code: 'ERR_MPLEX_STREAM_RESET'
  }
```
I'm unsure how this is happening despite the try catch, Is `source` itself also a promise?
If so perhaps it needs to be forced to settle with await first so any errors can be caught? e.g.
```
const sData = await source
for await (let data of sData ) {
```

**Comment by vasco-santos** [comment]
Hello @phillmac 

Thanks for reporting this. `source` is an async iterator. Can you provide me some context on how you are experiencing this?
It would be really helpful for trying to figure out this

**Comment by phillmac** [comment]
My best guess here is sometimes `source` is a rejected promise instead of the expected iterator?
I'm totally shooting in the dark however.
I'm using js-ipfs v0.46.0, nodejs v12.18.0
I've seen it several times recently, but I haven't been able to narrow down exactly which feature of ipfs triggers this

**Comment by vasco-santos** [comment]
Thanks for the details.
This seems the same issue as reported in [orbitdb/orbit-db-test-utils#18](https://github.com/orbitdb/orbit-db-test-utils/issues/18), and consequently being tracked on [libp2p/js-libp2p-tcp#130](https://github.com/libp2p/js-libp2p-tcp/issues/130). We will be looking into it.

**Comment by vasco-santos** [comment]
@phillmac We did some fixes regarding this with the latest `libp2p@0.28.3`. Could you try to reproduce it again?

**Comment by geolffreym** [comment]
any updates with this issue @vasco-santos 
```
(node:4001) UnhandledPromiseRejectionWarning: Error: stream reset
    at abortable (.../node_modules/abortable-iterator/index.js:29:19)
    at abortable.next (<anonymous>)
    at Object.sink (.../node_modules/libp2p-mplex/src/stream.js:76:24)
    at runMicrotasks (<anonymous>)
    at processTicksAndRejections (internal/process/task_queues.js:97:5)
(node:4001) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). To terminate the node process on unhandled promise rejection, use the CLI flag `--unhandled-rejections=strict` (see https://nodejs.org/api/cli.html#cli_unhandled_rejections_mode). (rejection id: 77565)

```

**Comment by vasco-santos** [comment]
It seems that the fix that came with `0.28.3` did not fix this entirely. We need to investigate this further

**Comment by vasco-santos** [comment]
This might be fixed by #122 . We need to test it

**Comment by mpetrunic** [comment]
closing as stale, shouldn't happen in latest release of mplex. Let us know if it's still happening
