### ISSUE TITLE
Version 1.0.0 and 1.0.1 I think they have a bug

### ISSUE THREAD

**Issue by fsvieira** [libp2p/js-libp2p-mplex#161]
Hi, 

I am new to libp2p and I was trying it for the first time, I started with the latest version of libp2p-mplex or @libp2p/mplex 
but I got this error : https://discuss.libp2p.io/t/trying-to-send-a-message-bettwen-two-nodes-but-got-exception-on-libp2p-mplex/1277

I got this error on both version 1.0.0 and 1.0.1, but then I replaced it to version v0.10.7 and it worked. 

I made a smaller ping version:

```
import Libp2p from 'libp2p'
import { NOISE } from 'libp2p-noise'
import  MPLEX  from 'libp2p-mplex'
import TCP from 'libp2p-tcp'
import { multiaddr } from 'multiaddr'

async function main (bootstrap) {
  const node = await Libp2p.create({
    addresses: {
      listen: ['/ip4/127.0.0.1/tcp/0']
    },
    modules: {
      transport: [TCP],
      connEncryption: [NOISE],
      streamMuxer: [MPLEX]
    },
  });

  const address = bootstrap[0];

  // start libp2p
  await node.start()
  console.log('libp2p has started')

  // print out listening addresses
  console.log('listening on addresses:')
  node.multiaddrs.forEach(addr => {
    console.log(`${addr.toString()}/p2p/${node.peerId.toB58String()}`)
  })

  // ping peer if received multiaddr
  if (address) {
    const ma = multiaddr(address)
    console.log(`pinging remote peer at ${address}`)
    const latency = await node.ping(ma)
    console.log(`pinged ${address} in ${latency}ms`)
  } else {
    console.log('no remote peer address given, skipping ping')
  }

  const stop = async () => {
    // stop libp2p
    await node.stop()
    console.log('libp2p has stopped')
    process.exit(0)
  }

  process.on('SIGTERM', stop)
  process.on('SIGINT', stop)

}

console.log(process.argv);

const [n, p, ...bootstrap] = process.argv;

main(bootstrap);

```

The error is the same with 1.0.0 and 1.0.1
```
Connection established to: QmSY1XoXy6vH44RQziyTSNmf99dk5vyC9tQ6PU49EgqigU /ip4/127.0.0.1/tcp/35071/p2p/QmSY1XoXy6vH44RQziyTSNmf99dk5vyC9tQ6PU49EgqigU
Connection established to: QmSY1XoXy6vH44RQziyTSNmf99dk5vyC9tQ6PU49EgqigU /ip4/127.0.0.1/tcp/35071/p2p/QmSY1XoXy6vH44RQziyTSNmf99dk5vyC9tQ6PU49EgqigU
file:///media/fsvieira/Data/fsvieira/sandbox/libp2p-repo/test/node_modules/uint8arraylist/dist/src/index.js:25
                length += buf.length;
                              ^

TypeError: Cannot read properties of undefined (reading 'length')
    at Uint8ArrayList.appendAll (file:///media/fsvieira/Data/fsvieira/sandbox/libp2p-repo/test/node_modules/uint8arraylist/dist/src/index.js:25:31)
    at Uint8ArrayList.subarray (file:///media/fsvieira/Data/fsvieira/sandbox/libp2p-repo/test/node_modules/uint8arraylist/dist/src/index.js:75:14)
    at Object.sink (file:///media/fsvieira/Data/fsvieira/sandbox/libp2p-repo/test/node_modules/libp2p-mplex/dist/src/stream.js:92:82)
    at processTicksAndRejections (node:internal/process/task_queues:96:5) {
  code: 'ERR_UNSUPPORTED_PROTOCOL'
}
```

But it works great with v0.10.7

Thanks.

**Comment by aomini** [comment]
yeah. Helpful thanks.
